blank_issues_enabled: false
contact_links:
  - name: Bug Reports
    url: https://github.com/DataDog/pathfinding.cloud/issues/new?template=bug.yaml
    about: Report a bug or an issue related to the repository by clicking here.

  - name: Feature Requests
    url: https://github.com/DataDog/pathfinding.cloud/issues/new?template=feature.yaml
    about: Suggest a new feature or enhancement for the project.
